### ISSUE TITLE
So whats the power-assert problem?

### ISSUE THREAD

**Issue by axe312ger** [sotojuan/redux-ava#16]
Thanks for all your work, it is doing its job! But the assertion errors are kind of useless actually. What's the reason it does not come with `power-assert` and are there workarounds?

IMHO it would be enough to get the processed new state from the reducer and just check via `t.deepEqual()` for equality. It comes with `power-assert`

Here are two screenshots how it looks at the moment. The output gives me no hint at all what could be wrong, just tells me sth is wrong :/

<img width="611" alt="screen shot 2017-01-17 at 10 31 09" src="https://cloud.githubusercontent.com/assets/1737026/22015099/e462685e-dca0-11e6-892f-05ae1106782d.png">
<img width="583" alt="screen shot 2017-01-17 at 10 32 08" src="https://cloud.githubusercontent.com/assets/1737026/22015098/e461563a-dca0-11e6-9f8e-fd387606f184.png">

**Comment by zcei** [comment]
You can find more information on that topic here: https://github.com/avajs/ava/issues/1049

The tl;dr is: there is a discussion ongoing to write an `ava/macro` module for distributable external macros (like this one)

**Comment by zcei** [comment]
According to https://github.com/avajs/ava/pull/1078 you might be able to add our helper path (within `node_modules`) to your glob of files that gets spawned by `ava`. Then you should get all the stuff you'd expect (ES6, power-assert, etc.)

**Comment by axe312ger** [comment]
Thanks for clarifying :)

So lets hope there will be some progress, I don't feel skilled enough to help there yet.

**Comment by zcei** [comment]
As there's nothing we can do *here*, but more likely in the `ava` repo itself, I'm going to close this one.
