### ISSUE TITLE
Immutable is() equality check issues and lack of helpful information

### ISSUE THREAD

**Issue by joeyfigaro** [sotojuan/redux-ava#7]
@sotojuan Thank you for all of your hard work! Things were going super smoothly until I started to run into equality issues on a few of my tests. 

I've checked to make sure my `stateAfter` object and the object returned from the reducer are both `List`s. 

**Results**
![](https://d3vv6lp55qjaqc.cloudfront.net/items/0k0Y120v1i1g282n2w3u/Image%202016-09-07%20at%204.08.00%20PM.png?X-CloudApp-Visitor-Id=d9b82902c609ab9b8edf70f3d783e6d6&v=af94efc9)

**Reducer**
```javascript
...
case ERROR_DISMISS:
    return state.remove(action.payload.id);
...
```

**Action**
```javascript
export const dismissError = (id) => ({
	type: ERROR_DISMISS,
	payload: { id }
});
```

**Test**
```javascript
test('[REDUCER][Errors] should dismiss individual errors', reducerTest(
	errorReducer,
	defaultErrors,
	dismissError(0),
	dismissedErrors
));
```

**Test Objects**
```javascript
const defaultErrors = List([
	{
		cause: 'Authentication',
		message: 'Invalid parameters: Password',
		meta: {}
	},
	{
		cause: 'Logout',
		message: 'Couldn\'t manage to logout.',
		meta: {}
	}
]);

const dismissedErrors = List([
	{
		cause: 'Logout',
		message: 'Couldn\'t manage to logout.',
		meta: {}
	}
]);
```

It'd be great if the objects supplied to `is()` were printed out along with the error somewhere?

**Comment by joeyfigaro** [comment]
Looks like this is [related to references to native objects](https://github.com/facebook/immutable-js/issues/675) - going to close this up. Hopefully it'll help other newcomers to Immutable.js. :)

**Comment by sotojuan** [comment]
Thanks for the info! Hope this helps others.
