### ISSUE TITLE
Multiple parameters for action creators

### ISSUE THREAD

**Issue by zcei** [sotojuan/redux-ava#9]
Hej,

as I was working with `tape` previously and `ava` currently, I used both `tape-redux` & `redux-ava`.

What I was lacking in both libs (as the `ava` one is just a port) was the possibility to pass multiple parameters to my action creators.

I tried looking up best practices with regard on single / multiple parameters, but couldn't find something. `redux`'s [`bindActionCreators`](https://github.com/reactjs/redux/blob/master/src/bindActionCreators.js#L2) passes down multiple parameters, so I think testing should allow this as well.

I created a repository ([redux-action-creator-test-enhancements](https://github.com/zcei/redux-action-creator-test-enhancements)) to demonstrate how I'd like to see this working.

The modified signature would look like this:

`actionTest(actionCreator[, ...data], expected[, description])`

With the current code the `package.json` should have `engines` set to `{ "node": ">=6.0.0" }`.
If this is a problem, I can down-port the implementation.

If you'd like to land this in your repository I'd be happy to file a PR to close this issue.

(See as well https://github.com/KaleoSoftware/tape-redux/issues/5)

**Comment by sotojuan** [comment]
Hi Stephan! This sounds like a great new feature but I do want to keep things usable in Node 4 at the least (and not introduce a Babel build step), so if you can find a way to do that a PR is welcome (since I don't have tests for this just make sure it works in a local project as well!).

**Comment by zcei** [comment]
Hej Juan,

porting this it no real problem. The only difference is to use a normal function instead of a fat-arrow one.
Then I can access `arguments` and convert it to `...params`.

Apart from this everything should be node v4 compatible.

**Comment by sotojuan** [comment]
Sounds good to me!
